import 'models.dart';

const List<VcpFeatureDefinition> kKnownVcpFeatures = <VcpFeatureDefinition>[
  VcpFeatureDefinition(
    code: 0x04,
    name: '恢复出厂设置',
    category: '系统',
    description: '向显示器发送恢复默认配置命令。',
    kind: VcpControlKind.action,
    actionValue: 1,
  ),
  VcpFeatureDefinition(
    code: 0x05,
    name: '恢复亮度/对比度',
    category: '亮度与对比度',
    description: '恢复亮度和对比度默认值。',
    kind: VcpControlKind.action,
    actionValue: 1,
  ),
  VcpFeatureDefinition(
    code: 0x06,
    name: '恢复几何设置',
    category: '几何',
    description: '恢复几何相关默认值，常见于 CRT 或兼容机型。',
    kind: VcpControlKind.action,
    actionValue: 1,
  ),
  VcpFeatureDefinition(
    code: 0x08,
    name: '恢复色彩设置',
    category: '色彩',
    description: '恢复色彩相关默认值。',
    kind: VcpControlKind.action,
    actionValue: 1,
  ),
  VcpFeatureDefinition(
    code: 0x0B,
    name: '色温增量',
    category: '色彩',
    description: '部分显示器用它调整色温步进。',
    kind: VcpControlKind.numeric,
  ),
  VcpFeatureDefinition(
    code: 0x0C,
    name: '色温请求',
    category: '色彩',
    description: '显示器暴露的色温相关数值。',
    kind: VcpControlKind.numeric,
  ),
  VcpFeatureDefinition(
    code: 0x10,
    name: '亮度',
    category: '亮度与对比度',
    description: '标准 MCCS 亮度控制。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x12,
    name: '对比度',
    category: '亮度与对比度',
    description: '标准 MCCS 对比度控制。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x14,
    name: '色彩预设',
    category: '色彩',
    description: '选择 sRGB、6500K、用户模式等显示预设。',
    kind: VcpControlKind.discrete,
    options: <VcpValueOption>[
      VcpValueOption(0x01, 'sRGB'),
      VcpValueOption(0x02, 'Display Native'),
      VcpValueOption(0x03, '4000K'),
      VcpValueOption(0x04, '5000K'),
      VcpValueOption(0x05, '6500K'),
      VcpValueOption(0x06, '7500K'),
      VcpValueOption(0x07, '8200K'),
      VcpValueOption(0x08, '9300K'),
      VcpValueOption(0x09, '10000K'),
      VcpValueOption(0x0A, '11500K'),
      VcpValueOption(0x0B, '用户 1'),
      VcpValueOption(0x0C, '用户 2'),
      VcpValueOption(0x0D, '用户 3'),
    ],
  ),
  VcpFeatureDefinition(
    code: 0x16,
    name: '红色增益',
    category: '色彩',
    description: 'RGB 增益中的红通道。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x18,
    name: '绿色增益',
    category: '色彩',
    description: 'RGB 增益中的绿通道。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x1A,
    name: '蓝色增益',
    category: '色彩',
    description: 'RGB 增益中的蓝通道。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x20,
    name: '水平位置',
    category: '几何',
    description: '图像水平位置。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x22,
    name: '水平尺寸',
    category: '几何',
    description: '图像水平尺寸。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x30,
    name: '垂直位置',
    category: '几何',
    description: '图像垂直位置。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x32,
    name: '垂直尺寸',
    category: '几何',
    description: '图像垂直尺寸。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x52,
    name: '激活控制',
    category: '系统',
    description: '部分显示器使用这个码切换内部控制状态。',
    kind: VcpControlKind.numeric,
  ),
  VcpFeatureDefinition(
    code: 0x60,
    name: '输入源',
    category: '输入与电源',
    description: '切换 VGA、DVI、HDMI、DP、USB-C 等输入口。',
    kind: VcpControlKind.discrete,
    readOftenUnsupported: true,
    options: <VcpValueOption>[
      VcpValueOption(0x01, 'VGA-1'),
      VcpValueOption(0x02, 'VGA-2'),
      VcpValueOption(0x03, 'DVI-1'),
      VcpValueOption(0x04, 'DVI-2'),
      VcpValueOption(0x05, 'Composite-1'),
      VcpValueOption(0x06, 'Composite-2'),
      VcpValueOption(0x07, 'S-Video-1'),
      VcpValueOption(0x08, 'S-Video-2'),
      VcpValueOption(0x09, 'Tuner-1'),
      VcpValueOption(0x0A, 'Tuner-2'),
      VcpValueOption(0x0B, 'Tuner-3'),
      VcpValueOption(0x0C, 'Component-1'),
      VcpValueOption(0x0D, 'Component-2'),
      VcpValueOption(0x0E, 'Component-3'),
      VcpValueOption(0x0F, 'DisplayPort-1'),
      VcpValueOption(0x10, 'DisplayPort-2'),
      VcpValueOption(0x11, 'HDMI-1'),
      VcpValueOption(0x12, 'HDMI-2'),
      VcpValueOption(0x13, 'USB-C'),
    ],
  ),
  VcpFeatureDefinition(
    code: 0x62,
    name: '音量',
    category: '音频',
    description: '内置扬声器音量。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x6C,
    name: '黑电平',
    category: '亮度与对比度',
    description: '整体黑电平。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x6E,
    name: '红色黑电平',
    category: '色彩',
    description: '红通道黑电平。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x70,
    name: '绿色黑电平',
    category: '色彩',
    description: '绿通道黑电平。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x72,
    name: '蓝色黑电平',
    category: '色彩',
    description: '蓝通道黑电平。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x86,
    name: '显示缩放',
    category: 'OSD 与图像',
    description: '控制显示比例、全屏或点对点等缩放策略。',
    kind: VcpControlKind.discrete,
  ),
  VcpFeatureDefinition(
    code: 0x87,
    name: '锐度',
    category: 'OSD 与图像',
    description: '图像锐化程度。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x8D,
    name: '静音',
    category: '音频',
    description: '内置扬声器静音开关。',
    kind: VcpControlKind.toggle,
    options: <VcpValueOption>[
      VcpValueOption(0x01, '开'),
      VcpValueOption(0x02, '关'),
    ],
  ),
  VcpFeatureDefinition(
    code: 0x8F,
    name: '音频高音',
    category: '音频',
    description: '部分显示器提供的高音调节。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0x90,
    name: '音频低音',
    category: '音频',
    description: '部分显示器提供的低音调节。',
    kind: VcpControlKind.continuous,
  ),
  VcpFeatureDefinition(
    code: 0xAA,
    name: '屏幕方向',
    category: 'OSD 与图像',
    description: '旋转或方向相关控制。',
    kind: VcpControlKind.discrete,
  ),
  VcpFeatureDefinition(
    code: 0xAC,
    name: '水平翻转',
    category: 'OSD 与图像',
    description: '镜像或翻转控制。',
    kind: VcpControlKind.toggle,
  ),
  VcpFeatureDefinition(
    code: 0xAE,
    name: '垂直翻转',
    category: 'OSD 与图像',
    description: '镜像或翻转控制。',
    kind: VcpControlKind.toggle,
  ),
  VcpFeatureDefinition(
    code: 0xB0,
    name: '设置保存',
    category: '系统',
    description: '部分显示器把它作为可写命令暴露，但通常读取不支持。',
    kind: VcpControlKind.action,
    actionValue: 1,
    readOftenUnsupported: true,
  ),
  VcpFeatureDefinition(
    code: 0xCA,
    name: 'OSD 开关',
    category: 'OSD 与图像',
    description: 'OSD 显示使能。',
    kind: VcpControlKind.toggle,
    readOftenUnsupported: true,
  ),
  VcpFeatureDefinition(
    code: 0xCC,
    name: 'OSD 语言',
    category: 'OSD 与图像',
    description: '显示器 OSD 菜单语言。',
    kind: VcpControlKind.discrete,
    readOftenUnsupported: true,
    options: <VcpValueOption>[
      VcpValueOption(0x01, '中文'),
      VcpValueOption(0x02, '英语'),
      VcpValueOption(0x03, '法语'),
      VcpValueOption(0x04, '德语'),
      VcpValueOption(0x05, '意大利语'),
      VcpValueOption(0x06, '西班牙语'),
      VcpValueOption(0x07, '日语'),
      VcpValueOption(0x08, '韩语'),
      VcpValueOption(0x09, '俄语'),
      VcpValueOption(0x0A, '葡萄牙语'),
    ],
  ),
  VcpFeatureDefinition(
    code: 0xD6,
    name: '电源模式',
    category: '输入与电源',
    description: '通常用于开机、待机、软关机等状态切换。',
    kind: VcpControlKind.discrete,
    readOftenUnsupported: true,
    options: <VcpValueOption>[
      VcpValueOption(0x01, '开机'),
      VcpValueOption(0x02, '待机'),
      VcpValueOption(0x03, '挂起'),
      VcpValueOption(0x04, '关机'),
      VcpValueOption(0x05, '软关机'),
    ],
  ),
  VcpFeatureDefinition(
    code: 0xDC,
    name: '显示模式',
    category: 'OSD 与图像',
    description: '部分显示器用于游戏、电影、阅读等场景模式。',
    kind: VcpControlKind.discrete,
  ),
  VcpFeatureDefinition(
    code: 0xDE,
    name: '扫描模式',
    category: 'OSD 与图像',
    description: '扫描或图像处理模式。',
    kind: VcpControlKind.discrete,
    readOftenUnsupported: true,
  ),
];

final Map<int, VcpFeatureDefinition> kKnownVcpFeatureMap =
    <int, VcpFeatureDefinition>{
  for (final VcpFeatureDefinition feature in kKnownVcpFeatures) feature.code: feature,
};
